import type { Metadata } from 'next';
import HeaderMenu from '@/components/HeaderMenu';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header className="flex flex-col items-center justify-center pb-2">
        <HeaderMenu color="secondary" />
      </header>
      {children}
    </>
  );
}
